
import React from 'react';
import { InventoryItem, MerchandisingSuggestion } from '../types';
import { PieChart, Pie, Cell, ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip } from 'recharts';
import { Share2, Download, CheckCircle2, Loader2 } from 'lucide-react';

interface ReportScreenProps {
  items: InventoryItem[];
  suggestions: MerchandisingSuggestion[];
}

const ReportScreen: React.FC<ReportScreenProps> = ({ items, suggestions }) => {
  const [isExporting, setIsExporting] = React.useState(false);

  const categoryData = React.useMemo(() => {
    const counts: Record<string, number> = {};
    items.forEach(item => {
      counts[item.category] = (counts[item.category] || 0) + item.quantity;
    });
    return Object.entries(counts).map(([name, value]) => ({ name, value }));
  }, [items]);

  const colorData = React.useMemo(() => {
    const counts: Record<string, number> = {};
    items.forEach(item => {
      counts[item.color] = (counts[item.color] || 0) + item.quantity;
    });
    return Object.entries(counts).map(([name, value]) => ({ name, value }));
  }, [items]);

  const COLORS = ['#6366f1', '#8b5cf6', '#ec4899', '#f43f5e', '#f59e0b', '#10b981'];

  const handleExportPDF = () => {
    setIsExporting(true);
    // Give a small delay for feedback
    setTimeout(() => {
      window.print();
      setIsExporting(false);
    }, 500);
  };

  const handleShare = async () => {
    const totalItems = items.reduce((acc, curr) => acc + curr.quantity, 0);
    const topCategory = categoryData.sort((a, b) => b.value - a.value)[0]?.name || 'N/A';
    
    const shareData = {
      title: 'LEIVIP Inventory Intelligence Report',
      text: `Inventory Summary for ${new Date().toLocaleDateString()}:
- Total Items: ${totalItems}
- Top Category: ${topCategory}
- Unique Categories: ${categoryData.length}
- Optimization Strategies Applied: ${suggestions.filter(s => s.isApplied).length}

Generated by LEIVIP AI.`,
      url: window.location.href
    };

    if (navigator.share) {
      try {
        await navigator.share(shareData);
      } catch (err) {
        console.error('Error sharing:', err);
      }
    } else {
      // Fallback: Copy to clipboard
      try {
        await navigator.clipboard.writeText(`${shareData.text}\nView at: ${shareData.url}`);
        alert('Report summary copied to clipboard!');
      } catch (err) {
        alert('Sharing is not supported on this browser.');
      }
    }
  };

  return (
    <div className="space-y-6 pb-20 animate-in fade-in zoom-in duration-700">
      <div className="bg-gradient-to-br from-indigo-600 to-violet-700 p-6 rounded-3xl text-white space-y-4 shadow-xl shadow-indigo-900/30">
        <div className="flex justify-between items-start">
          <div className="space-y-1">
            <h2 className="text-2xl font-bold">Store Report</h2>
            <p className="text-indigo-100 text-sm opacity-90">{new Date().toLocaleDateString()} • Floor Stock #102</p>
          </div>
          <div className="bg-white/20 p-2 rounded-xl backdrop-blur-sm">
            <CheckCircle2 size={24} />
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4 pt-2">
          <div className="bg-white/10 p-3 rounded-2xl backdrop-blur-md">
            <p className="text-indigo-200 text-[10px] font-bold uppercase mb-1">Total Pieces</p>
            <p className="text-2xl font-bold">{items.reduce((acc, curr) => acc + curr.quantity, 0)}</p>
          </div>
          <div className="bg-white/10 p-3 rounded-2xl backdrop-blur-md">
            <p className="text-indigo-200 text-[10px] font-bold uppercase mb-1">Categories</p>
            <p className="text-2xl font-bold">{categoryData.length}</p>
          </div>
        </div>
      </div>

      <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 space-y-6">
        <h3 className="font-bold text-lg">Category Distribution</h3>
        <div className="h-64 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <PieChart>
              <Pie
                data={categoryData}
                cx="50%"
                cy="50%"
                innerRadius={60}
                outerRadius={80}
                paddingAngle={5}
                dataKey="value"
              >
                {categoryData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                ))}
              </Pie>
              <Tooltip 
                contentStyle={{ backgroundColor: '#0f172a', border: '1px solid #1e293b', borderRadius: '8px' }}
                itemStyle={{ color: '#f8fafc' }}
              />
            </PieChart>
          </ResponsiveContainer>
        </div>
        <div className="grid grid-cols-2 gap-2">
          {categoryData.map((cat, idx) => (
            <div key={cat.name} className="flex items-center gap-2">
              <div className="w-3 h-3 rounded-full" style={{ backgroundColor: COLORS[idx % COLORS.length] }} />
              <span className="text-xs text-slate-400 capitalize">{cat.name} ({cat.value})</span>
            </div>
          ))}
        </div>
      </div>

      <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 space-y-6">
        <h3 className="font-bold text-lg">Color Analytics</h3>
        <div className="h-64 w-full">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={colorData}>
              <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: '#94a3b8' }} />
              <YAxis hide />
              <Tooltip 
                cursor={{ fill: '#1e293b' }}
                contentStyle={{ backgroundColor: '#0f172a', border: '1px solid #1e293b', borderRadius: '8px' }}
              />
              <Bar dataKey="value" fill="#6366f1" radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Optimization Strategies Summary Section for Report */}
      {suggestions.some(s => s.isApplied) && (
        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 space-y-4">
          <h3 className="font-bold text-lg">Applied Optimization Strategies</h3>
          <div className="space-y-3">
            {suggestions.filter(s => s.isApplied).map((s, idx) => (
              <div key={idx} className="flex gap-3 items-start border-l-2 border-indigo-500 pl-4 py-1">
                <div>
                  <h4 className="text-sm font-bold text-slate-100">{s.title}</h4>
                  <p className="text-xs text-slate-400">{s.description}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="grid grid-cols-2 gap-3 no-print">
        <button 
          onClick={handleExportPDF}
          disabled={isExporting}
          className="bg-slate-800 hover:bg-slate-700 p-4 rounded-2xl flex flex-col items-center gap-2 transition-all active:scale-95 disabled:opacity-50"
        >
          {isExporting ? <Loader2 size={20} className="text-indigo-400 animate-spin" /> : <Download size={20} className="text-indigo-400" />}
          <span className="text-xs font-bold">{isExporting ? 'Preparing...' : 'PDF Export'}</span>
        </button>
        <button 
          onClick={handleShare}
          className="bg-slate-800 hover:bg-slate-700 p-4 rounded-2xl flex flex-col items-center gap-2 transition-all active:scale-95"
        >
          <Share2 size={20} className="text-indigo-400" />
          <span className="text-xs font-bold">Share Report</span>
        </button>
      </div>

      <div className="text-center p-8 border-t border-slate-800">
        <p className="text-slate-500 text-[10px] uppercase tracking-widest font-bold">Powered by LEIVIP AI Intelligence</p>
      </div>
    </div>
  );
};

export default ReportScreen;
